#!/usr/bin/env python3
"""Add more English sentences - part 6: science and math."""
import sys
sys.stdout.reconfigure(encoding='utf-8')

part6 = [
    "Calculus studies continuous change through derivatives and integrals.",
    "Derivatives measure instantaneous rate of change of functions.",
    "Integrals compute accumulated quantities under curves.",
    "Fundamental theorem of calculus connects derivatives and integrals.",
    "Taylor series approximates functions using polynomial expansions.",
    "Fourier analysis decomposes signals into frequency components.",
    "Differential equations describe relationships between functions and derivatives.",
    "Partial differential equations involve multivariable functions and derivatives.",
    "Ordinary differential equations involve single variable derivatives.",
    "Linear algebra studies vector spaces and linear transformations.",
    "Eigenvalues characterize linear transformations and systems.",
    "Eigenvectors define directions of linear transformation stretching.",
    "Matrix decomposition factors matrices into simpler components.",
    "Singular value decomposition provides optimal low-rank matrix approximation.",
    "LU decomposition factors matrices into lower and upper triangular.",
    "Cholesky decomposition factors symmetric positive definite matrices.",
    "QR decomposition expresses matrices as orthogonal and triangular products.",
    "Principal component analysis uses eigenvalue decomposition of covariance.",
    "Probability theory quantifies uncertainty through mathematical models.",
    "Random variables map outcomes to numerical values.",
    "Probability distributions describe how random variables take values.",
    "Normal distribution describes many natural phenomena symmetrically.",
    "Poisson distribution models count data for rare events.",
    "Binomial distribution models successes in fixed Bernoulli trials.",
    "Exponential distribution models time between consecutive events.",
    "Uniform distribution assigns equal probability to all outcomes.",
    "Beta distribution models probabilities and proportions flexibly.",
    "Gamma distribution models waiting times for multiple events.",
    "Chi-square distribution arises in variance testing contexts.",
    "Student's t-distribution handles small sample mean inference.",
    "F-distribution compares variances between two normal populations.",
    "Central limit theorem states sample means approach normal distribution.",
    "Law of large numbers states sample averages converge to expectation.",
    "Bayes theorem updates probabilities given new evidence.",
    "Conditional probability measures likelihood given prior information.",
    "Joint probability measures likelihood of simultaneous events occurring.",
    "Marginal probability sums joint probabilities over unwanted variables.",
    "Independence means joint probability equals product of marginals.",
    "Covariance measures linear association between two random variables.",
    "Correlation normalizes covariance to unitless association measure.",
    "Entropy measures information content and uncertainty.",
    "Mutual information quantifies shared information between variables.",
    "Cross-entropy measures difference between predicted and true distributions.",
    "KL divergence measures information loss from distribution approximation.",
    "Physics studies matter, energy, and their fundamental interactions.",
    "Classical mechanics describes motion of macroscopic objects.",
    "Newton's laws describe forces and resulting object motion.",
    "Conservation of energy states energy cannot be created or destroyed.",
    "Conservation of momentum states total momentum remains constant.",
    "Thermodynamics studies heat, work, and energy transformations.",
    "First law of thermodynamics states energy is conserved.",
    "Second law of thermodynamics states entropy always increases.",
    "Third law of thermodynamics states absolute zero is unattainable.",
    "Electromagnetic theory describes electric and magnetic field interactions.",
    "Maxwell's equations unify electricity and magnetism mathematically.",
    "Special relativity describes physics at speeds approaching light.",
    "General relativity describes gravity as spacetime curvature.",
    "Quantum mechanics describes physics at atomic scales.",
    "Heisenberg uncertainty principle limits simultaneous measurement precision.",
    "Schrödinger equation describes quantum state evolution over time.",
    "Quantum superposition allows particles to exist in multiple states.",
    "Quantum entanglement links particles regardless of spatial separation.",
    "Wave-particle duality describes light and matter behavior.",
    "Chemistry studies substances, their properties, and reactions.",
    "Atomic theory describes structure of atoms and subatomic particles.",
    "Chemical bonding forms molecules through electron interactions.",
    "Organic chemistry studies carbon-based compound structures and reactions.",
    "Biochemistry applies chemistry to biological systems and processes.",
    "Molecular biology studies biological processes at molecular level.",
    "Genetics studies heredity and variation of organisms.",
    "DNA encodes genetic information using nucleotide sequences.",
    "RNA translates genetic code into protein instructions.",
    "Proteins fold into three-dimensional structures determining function.",
    "Enzymes catalyze biochemical reactions in living organisms.",
    "Cell biology studies structure and function of cells.",
    "Cell division produces new cells through mitosis and meiosis.",
    "Metabolism encompasses all chemical reactions in organisms.",
    "Photosynthesis converts light energy into chemical energy.",
    "Cellular respiration converts glucose into usable energy.",
    "Ecology studies interactions between organisms and their environment.",
    "Ecosystems consist of living organisms and their physical environment.",
    "Biodiversity measures variety of life in an ecosystem.",
    "Evolution describes changes in species over generations.",
    "Natural selection favors traits improving survival and reproduction.",
    "Genetic drift causes random changes in gene frequency.",
    "Speciation creates new species through reproductive isolation.",
    "Geology studies Earth's structure, composition, and processes.",
    "Plate tectonics describes movement of Earth's lithospheric plates.",
    "Volcanism releases magma from Earth's interior to surface.",
    "Erosion shapes landscapes through weathering and transportation.",
    "Sedimentation deposits particles creating sedimentary rock layers.",
    "Astronomy studies celestial objects and phenomena beyond Earth.",
    "Cosmology studies origin and evolution of the universe.",
    "The Big Bang theory describes universe expansion from initial state.",
    "Dark matter influences galactic rotation without emitting light.",
    "Dark energy drives accelerating expansion of the universe.",
    "Stellar evolution describes life cycle of stars.",
    "Black holes trap light through extreme gravitational attraction.",
    "Nuclear fusion powers stars through hydrogen-to-helium conversion.",
    "Mathematical logic formalizes reasoning using symbolic systems.",
    "Set theory studies collections of objects and their relationships.",
    "Graph theory analyzes networks of nodes and connections.",
    "Number theory studies properties and relationships of integers.",
    "Combinatorics counts and organizes discrete structures.",
    "Topology studies properties preserved under continuous deformations.",
    "Category theory abstracts mathematical structures and their relationships.",
    "Measure theory provides foundation for probability and integration.",
    "Real analysis rigorously studies real numbers and functions.",
    "Complex analysis studies functions of complex variables.",
    "Abstract algebra studies algebraic structures like groups and rings.",
    "Group theory studies symmetry and algebraic group structures.",
    "Ring theory studies algebraic structures with two operations.",
    "Field theory studies algebraic structures supporting arithmetic.",
    "Lattice theory studies partially ordered sets with meet and join.",
    "Order theory studies binary relations with transitivity properties.",
    "Combinatorial optimization finds optimal discrete configurations.",
    "Integer optimization restricts decision variables to whole numbers.",
    "Nonlinear optimization handles objective functions with nonlinear terms.",
    "Constrained optimization includes equality and inequality constraints.",
    "Unconstrained optimization minimizes functions without restriction.",
    "Global optimization seeks best solution across entire search space.",
    "Local optimization finds best solution in neighborhood.",
    "Multi-objective optimization balances competing objective functions.",
    "Robust optimization handles uncertainty in problem parameters.",
    "Stochastic optimization incorporates randomness into search process.",
    "Evolutionary optimization uses population-based search strategies.",
    "Swarm intelligence optimization uses collective behavior models.",
]

with open('data/raw/english_expand_part6.txt', 'w', encoding='utf-8') as f:
    for s in part6:
        f.write(s + '\n')
print(f"Part 6: {len(part6)}")
