#!/usr/bin/env python3
"""Add more English sentences - part 8."""
import sys
sys.stdout.reconfigure(encoding='utf-8')

part8 = [
    "Carbon footprints measure greenhouse gas emissions from activities.",
    "Renewable energy sources reduce dependence on fossil fuels.",
    "Solar panels convert sunlight into usable electrical energy.",
    "Wind turbines generate electricity from moving air currents.",
    "Hydroelectric power harnesses flowing water for energy generation.",
    "Geothermal energy uses Earth's internal heat for power.",
    "Biomass energy converts organic materials into usable fuel.",
    "Energy storage systems preserve electricity for later consumption.",
    "Battery technology stores electrical energy in chemical form.",
    "Hydrogen fuel cells generate electricity through chemical reactions.",
    "Electric vehicles reduce emissions compared to combustion engines.",
    "Autonomous vehicles navigate without human driver intervention.",
    "Traffic management systems optimize vehicle flow through signals.",
    "Public transportation reduces individual carbon footprints significantly.",
    "Urban planning designs cities for livability and efficiency.",
    "Sustainable architecture minimizes environmental impact of buildings.",
    "Green building materials reduce construction environmental impact.",
    "Smart grids optimize electricity distribution using digital technology.",
    "Water purification removes contaminants from water for consumption.",
    "Waste management handles refuse through collection and processing.",
    "Recycling converts waste materials into new useful products.",
    "Composting transforms organic waste into nutrient-rich soil.",
    "Circular economy redesigns systems to eliminate waste completely.",
    "Life cycle assessment evaluates environmental impact throughout existence.",
    "Environmental monitoring tracks pollution levels in air and water.",
    "Climate change alters global weather patterns over time.",
    "Carbon capture removes CO2 from atmosphere or emission sources.",
    "Ocean acidification reduces seawater pH threatening marine ecosystems.",
    "Deforestation removes forests reducing biodiversity and carbon storage.",
    "Reforestation replants trees to restore damaged forest ecosystems.",
    "Conservation biology protects species and their natural habitats.",
    "Endangered species face extinction risk from various threats.",
    "Wildlife corridors connect fragmented habitats for animal movement.",
    "Marine protected areas conserve ocean ecosystems and biodiversity.",
    "Coral reefs support diverse marine life in tropical oceans.",
    "Wetlands filter water and provide critical wildlife habitat.",
    "Freshwater ecosystems support drinking water and biodiversity.",
    "Soil health determines agricultural productivity and ecosystem function.",
    "Agroecology applies ecological principles to agricultural systems.",
    "Permaculture designs sustainable human settlement patterns.",
    "Organic farming avoids synthetic chemicals in food production.",
    "Hydroponics grows plants without soil using nutrient solutions.",
    "Aquaponics combines fish farming with hydroponic plant cultivation.",
    "Vertical farming grows crops in stacked indoor layers.",
    "Precision agriculture uses technology for targeted crop management.",
    "Drone agriculture surveys crops using aerial imaging technology.",
    "Satellite imagery monitors global land use and changes.",
    "Remote sensing measures Earth properties from satellite platforms.",
    "Geographic information systems analyze spatial data and relationships.",
    "Cartography creates maps representing geographic information visually.",
    "Navigation systems determine optimal routes between locations.",
    "Global positioning systems provide location coordinates worldwide.",
    "Seismology studies earthquakes and seismic wave propagation.",
    "Meteorology studies atmospheric conditions and weather forecasting.",
    "Oceanography studies physical and biological ocean properties.",
    "Limnology studies inland water bodies and their ecosystems.",
    "Volcanology studies volcanic activity and eruption processes.",
    "Glaciology studies glaciers and ice sheet dynamics.",
    "Paleontology studies ancient life through fossil evidence.",
    "Archaeology studies human history through material remains.",
    "Anthropology studies human societies and cultural development.",
    "Sociology studies social behavior and institutional structures.",
    "Psychology studies mind, behavior, and mental processes.",
    "Cognitive psychology studies mental processes like thinking.",
    "Developmental psychology studies human growth and change.",
    "Social psychology studies how people influence each other.",
    "Clinical psychology assesses and treats mental health conditions.",
    "Educational psychology studies learning processes and teaching methods.",
    "Organizational psychology studies workplace behavior and performance.",
    "Behavioral economics combines psychology and economic decision theory.",
    "Neuroscience studies nervous system structure and function.",
    "Cognitive neuroscience links brain activity to mental processes.",
    "Computational neuroscience models brain function mathematically.",
    "Brain-computer interfaces enable direct neural communication with devices.",
    "Neural prosthetics replace damaged neural tissue function.",
    "Brain mapping identifies functional regions of the brain.",
    "Electroencephalography records electrical activity of the brain.",
    "Functional MRI measures brain activity through blood flow.",
    "Positron emission tomography visualizes metabolic processes in brain.",
    "Diffusion tensor imaging maps neural connectivity in brain.",
    "Transcranial magnetic stimulation modulates brain activity noninvasively.",
    "Pharmacology studies drug actions on biological systems.",
    "Toxicology studies adverse effects of chemical substances.",
    "Immunology studies immune system structure and function.",
    "Vaccination stimulates immune protection against specific pathogens.",
    "Antibiotics treat bacterial infections through targeted mechanisms.",
    "Antiviral drugs inhibit viral replication in host cells.",
    "Gene therapy introduces functional genes to treat diseases.",
    "CRISPR gene editing modifies DNA sequences precisely.",
    "Stem cell research explores regenerative medicine possibilities.",
    "Tissue engineering creates biological substitutes for damaged tissues.",
    "3D bioprinting creates living tissue structures layer by layer.",
    "Organoids are miniature organ models grown in laboratories.",
    "Personalized medicine tailors treatments to individual patient genetics.",
    "Pharmacogenomics studies genetic influence on drug responses.",
    "Biomarkers indicate biological states or conditions in organisms.",
    "Clinical trials test medical interventions for safety and efficacy.",
    "Randomized controlled trials establish treatment effectiveness rigorously.",
    "Systematic reviews synthesize evidence from multiple research studies.",
    "Meta-analysis combines statistical results from related studies.",
    "Evidence-based medicine integrates research evidence into clinical practice.",
    "Translational research converts laboratory discoveries into treatments.",
    "Precision diagnostics identify specific disease subtypes accurately.",
    "Point-of-care testing provides rapid diagnostic results at bedside.",
    "Liquid biopsies detect cancer biomarkers in blood samples.",
    "Radiology interprets medical images for diagnostic purposes.",
    "Interventional radiology uses imaging for minimally invasive procedures.",
    "Nuclear medicine uses radioactive substances for diagnosis and treatment.",
    "Radiation therapy targets cancer cells with ionizing radiation.",
    "Proton therapy uses proton beams for targeted cancer treatment.",
    "Immunotherapy harnesses immune system to fight cancer.",
    "CAR-T cell therapy engineers patient cells to attack cancer.",
    "Monoclonal antibodies target specific molecules for therapeutic effect.",
    "Biomaterials interact with biological systems for medical applications.",
    "Nanomedicine applies nanotechnology to medical diagnosis and treatment.",
    "Drug delivery systems control medication release in the body.",
    "Controlled-release formulations provide sustained medication dosing.",
    "Nanoparticles carry drugs to specific target cells.",
    "Liposomes encapsulate drugs for improved delivery efficiency.",
    "Antibody-drug conjugates combine targeting antibodies with cytotoxic drugs.",
    "Microbiome studies examine communities of microorganisms in the body.",
    "Gut bacteria influence digestion, immunity, and overall health.",
    "Probiotics introduce beneficial microorganisms into digestive system.",
    "Prebiotics feed beneficial gut bacteria promoting healthy microbiome.",
    "Metabolomics studies chemical processes involving metabolites in organisms.",
    "Proteomics studies entire protein complement expressed by organisms.",
    "Transcriptomics studies complete set of RNA transcripts produced.",
    "Epigenetics studies heritable changes without DNA sequence alterations.",
    "Gene expression调控 determines which genes are active in cells.",
    "Signal transduction transmits cellular signals from receptors to targets.",
    "Cell communication coordinates multicellular organism activities.",
    "Stem cells differentiate into specialized cell types.",
    "Programmed cell death eliminates unwanted or damaged cells.",
    "Autophagy degrades and recycles cellular components.",
    "Cellular aging reduces cell function over time.",
    "Telomere shortening limits cell division capacity.",
    "Senescent cells stop dividing but remain metabolically active.",
]

with open('data/raw/english_expand_part8.txt', 'w', encoding='utf-8') as f:
    for s in part8:
        f.write(s + '\n')
print(f"Part 8: {len(part8)}")
